{- PuzzlePrinter.hs
 - Copyright 2012 Thomas Schreiber <ubiquill@gmail.com>
 -
 - Formats word puzzles in LaTeX.
 -}
 
module PuzzlePrinter where

import System.IO
import WordSearch

boilerPlate = "\\documentclass[12pt]{article}\n"
           ++ "\\usepackage{cwpuzzle}\n"
           ++ "\\usepackage{fullpage}\n"
           ++ "\\usepackage{multicol}\n"
           ++ "\\begin{document}\n"
           ++ "\\title{Word Search}\n"
           ++ "\\author{Generated by Haskword}\n"
           ++ "\\maketitle\n"


writeBaseLaTeX :: IO ()
writeBaseLaTeX  = do h <- openFile "test.tex" WriteMode
                     hPutStr h boilerPlate
                     hClose h

latexPuzzle  :: IO Grid -> IO String
latexPuzzle g = do grid <- g
                   return (puzzleFormat grid)

latexWords   :: [String] -> String
latexWords ws = "\\begin{center}\n"
             ++ "\\begin{multicols}{3}\n"
             ++ "\\begin{itemize}\n"
             ++ concat (map (\w -> "\\item " ++ w ++ "\n") ws)
             ++ "\\end{itemize}\n"
             ++ "\\end{multicols}\n"
             ++ "\\end{center}\n"
    
puzzleChar  :: Char -> String
puzzleChar c = "|[][S]" ++ [c] ++ " "

puzzleLine :: String -> String
puzzleLine  = concat . map puzzleChar

puzzleGrid :: Grid -> [String]
puzzleGrid = map puzzleLine

puzzleFormat  :: Grid -> String
puzzleFormat g = "\\begin{Puzzle}{" ++ show (length g) 
              ++ "}{" ++ show (length (head g)) ++ "}\n"
              ++ concat (map (++ "|.\n") (puzzleGrid g))
              ++ "\\end{Puzzle}\n"

writePuzzle       :: FilePath -> IO Grid -> [String] -> IO ()
writePuzzle f g ws = do p <- puzzle
                        h <- openFile f WriteMode
                        hPutStr h p
                        hClose h
                        where puzzle = do gp <- latexPuzzle g
                                          return (boilerPlate 
                                               ++ gp 
                                               ++ latexWords ws
                                               ++ "\\end{document}\n")


